'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DeckOfCardsTest.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AceofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AceofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AceofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AceofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AceofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AceofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AceofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AceofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cardback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EightofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EightofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EightofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EightofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EightofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EightofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EightofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EightofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FiveofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FiveofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FiveofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FiveofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FiveofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FiveofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FiveofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FiveofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FourofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FourofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FourofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FourofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FourofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FourofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FourofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FourofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JackofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JackofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JackofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JackofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JackofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JackofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JackofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JackofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KingofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KingofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KingofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KingofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KingofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KingofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KingofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KingofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NineofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NineofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NineofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NineofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NineofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NineofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NineofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NineofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueenofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueenofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueenofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueenofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueenofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueenofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueenofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueenofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SevenofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SevenofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SevenofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SevenofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SixofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SixofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SixofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SixofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SixofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SixofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SixofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SixofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TenofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TenofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TenofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TenofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TenofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TenofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TenofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TenofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThreeofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreeofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThreeofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreeofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThreeofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreeofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThreeofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreeofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TwoofClubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoofClubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TwoofDiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoofDiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TwoofHearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoofHearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TwoofSpades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwoofSpades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
