'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Title
    Public Property ISBN As String
    Public Property Title1 As String
    Public Property EditionNumber As Integer
    Public Property Copyright As String

    Public Overridable Property Authors As ICollection(Of Author) = New HashSet(Of Author)

End Class
