'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AnimationDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property deitel0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deitel9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deitel9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
