'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Validation

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''nameTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents nameTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''nameRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents nameRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''emailTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''emailRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''emailRegularExpressionValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

   '''<summary>
   '''phoneTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''phoneRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''phoneRegularExpressionValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

   '''<summary>
   '''submitButton control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''outputLabel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents outputLabel As Global.System.Web.UI.WebControls.Label
End Class
