'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Validation

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''ToolkitScriptManager1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

   '''<summary>
   '''TabContainer1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

   '''<summary>
   '''TabPanel1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

   '''<summary>
   '''nameTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents nameTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''nameRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents nameRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''nameRequiredFieldValidator_ValidatorCalloutExtender control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents nameRequiredFieldValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

   '''<summary>
   '''TabPanel2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

   '''<summary>
   '''emailTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''emailRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''emailRequiredFieldValidator_ValidatorCalloutExtender control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRequiredFieldValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

   '''<summary>
   '''emailRegularExpressionValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

   '''<summary>
   '''emailRegularExpressionValidator_ValidatorCalloutExtender control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents emailRegularExpressionValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

   '''<summary>
   '''phoneTextBox control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneTextBox As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''phoneRequiredFieldValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

   '''<summary>
   '''phoneRequiredFieldValidator_ValidatorCalloutExtender control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRequiredFieldValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

   '''<summary>
   '''phoneRegularExpressionValidator control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

   '''<summary>
   '''phoneRegularExpressionValidator_ValidatorCalloutExtender control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents phoneRegularExpressionValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

   '''<summary>
   '''UpdatePanel1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''submitButton control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''outputLabel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents outputLabel As Global.System.Web.UI.WebControls.Label
End Class
